### ISSUE TITLE
Webcam Firefox hack: Better use about:permissions

### ISSUE THREAD

**Issue by rugk** [thieman/github-selfies#64]
Instead of the [dangerous](https://github.com/thieman/github-selfies/issues/57) Firefox `about:config` hack, I'd say that it would be much more secure to use `about:permissions`, look for github.com and adjust the permissions here.
You should never adjust security settings such badly just for a single feature on *one* website. So with `about:permissions` that's a much better way to do it.

I did not tested this, but I think it should work.

**Comment by thieman** [comment]
You're right, that hack is quite awful and was only even considered because Firefox was really obnoxious about asking about it every time. We could look to see if the permissions thing is a better fix.

However, I think this might also be a good time to admit that the Firefox version of the plugin didn't really take off and deprecate it for now. I'm sure it's not working anyway, since the Chrome version itself still has a few kinks and the Firefox version is many releases behind.

**Comment by rugk** [comment]
> However, I think this might also be a good time to admit that the Firefox version of the plugin didn't really take off and deprecate it for now. I'm sure it's not working anyway, since the Chrome version itself still has a few kinks and the Firefox version is many releases behind.

Okay, I did not tested it.
But anyway this 'guide' should be corrected, so no one uses it as a model - even if the extension does not work at all. (so that users would trying to adjust every crappy setting just to get it working until they realize it's the addon itself :wink:)

**Comment by thieman** [comment]
Agreed, will get rid of it as part of the Firefox deprecation PR

**Comment by rugk** [comment]
:+1:
